// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCixotihMZIi-cYUpOjSYgs7ReiIiW-tdo',
    appId: '1:194426985636:web:c6cb1e0562d4a4f8cc1a31',
    messagingSenderId: '194426985636',
    projectId: 'smart-class-d7b20',
    authDomain: 'smart-class-d7b20.firebaseapp.com',
    storageBucket: 'smart-class-d7b20.firebasestorage.app',
    measurementId: 'G-Q9SZLHQCPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUDnI-C4IGlV7WmaPb8ASTNhmVDEhfIU',
    appId: '1:194426985636:android:1aac903c729b6f57cc1a31',
    messagingSenderId: '194426985636',
    projectId: 'smart-class-d7b20',
    storageBucket: 'smart-class-d7b20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5d6YjEMknbN7zXGIhkhi909WqIH3-pfE',
    appId: '1:194426985636:ios:65417f98461a3f8fcc1a31',
    messagingSenderId: '194426985636',
    projectId: 'smart-class-d7b20',
    storageBucket: 'smart-class-d7b20.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5d6YjEMknbN7zXGIhkhi909WqIH3-pfE',
    appId: '1:194426985636:ios:65417f98461a3f8fcc1a31',
    messagingSenderId: '194426985636',
    projectId: 'smart-class-d7b20',
    storageBucket: 'smart-class-d7b20.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCixotihMZIi-cYUpOjSYgs7ReiIiW-tdo',
    appId: '1:194426985636:web:bb8c6afca9cb4c0ccc1a31',
    messagingSenderId: '194426985636',
    projectId: 'smart-class-d7b20',
    authDomain: 'smart-class-d7b20.firebaseapp.com',
    storageBucket: 'smart-class-d7b20.firebasestorage.app',
    measurementId: 'G-T62J9G1SJX',
  );
}
